### ISSUE TITLE
Path with spaces.

### ISSUE THREAD

**Issue by GGG-KILLER** [paulpflug/autocompile-jade#1]
When using a path which has spaces on it, the auto-compiling process gives an error:

```
fs.js:887
  return binding.lstat(pathModule._makeLong(path));
                                  ^

Error: ENOENT: no such file or directory, lstat 'C:\Users\GGG\AppData\Local\atom\app-1.2.4\to'
    at Error (native)
    at Object.fs.lstatSync (fs.js:887:18)
    at renderFile (C:\Users\GGG\.atom\packages\autocompile-jade\node_modules\jade\bin\jade.js:227:17)
    at C:\Users\GGG\.atom\packages\autocompile-jade\node_modules\jade\bin\jade.js:136:5
    at Array.forEach (native)
    at Object.<anonymous> (C:\Users\GGG\.atom\packages\autocompile-jade\node_modules\jade\bin\jade.js:135:9)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
```

in the case, the folder name was `html to js`

**Comment by paulpflug** [comment]
should work in 0.0.2. Sorry it took so long.

**Comment by GGG-KILLER** [comment]
No problem, thanks for fixing it!

**Comment by GGG-KILLER** [comment]
Sorry, but I just tested and it gave an error again:

```
compiling failed

fs.js:887
  return binding.lstat(pathModule._makeLong(path));
                                  ^

Error: ENOENT: no such file or directory, lstat 'C:\WINDOWS\system32\"C:\Users\GGG\Desktop\[en]SQL Simulator\index.jade"'
    at Error (native)
    at Object.fs.lstatSync (fs.js:887:18)
    at renderFile (C:\Users\GGG\.atom\packages\autocompile-jade\node_modules\jade\bin\jade.js:227:17)
    at C:\Users\GGG\.atom\packages\autocompile-jade\node_modules\jade\bin\jade.js:136:5
    at Array.forEach (native)
    at Object.<anonymous> (C:\Users\GGG\.atom\packages\autocompile-jade\node_modules\jade\bin\jade.js:135:9)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
```

**Comment by paulpflug** [comment]
Seems windows specific now. Probably because the path doesn't exist? At 
least the path isn't cut like before 😀

Am 14. Dezember 2015 00:13:33 schrieb GGG KILLER notifications@github.com:

**Comment by GGG-KILLER** [comment]
The path does exist, and it is cutting it, it was originally a folder on the Desktop, but now it is looking for it on System32.
The full path was `C:\Users\GGG\Desktop\[en]SQL Simulator`

**Comment by paulpflug** [comment]
could you try 0.0.3?
if it isn't working yet, I need more information:
- full name of the jade source file
- what you wrote in the comment in the first line
- where the output is expected
- error (if different from above)

thx

**Comment by GGG-KILLER** [comment]
I've already tried doing what you did on your latest commit, however it did not solve the problem.

This is the full information:
- Full name of the jade source file: `C:\Users\GGG\Desktop\[en]SQL Simulator\index.jade`
- What I wrote in the comment in the first line: `//- out: .,   compress: true`
- Where the output is expected: `C:\Users\GGG\Desktop\[en]SQL Simulator\index.html`
- Error message:

```
compiling failed
fs.js:887
  return binding.lstat(pathModule._makeLong(path));
                                  ^

Error: ENOENT: no such file or directory, lstat 'C:\Users\GGG\Desktop\Simulator"'
    at Error (native)
    at Object.fs.lstatSync (fs.js:887:18)
    at renderFile (C:\Users\GGG\.atom\packages\autocompile-jade\node_modules\jade\bin\jade.js:227:17)
    at C:\Users\GGG\.atom\packages\autocompile-jade\node_modules\jade\bin\jade.js:136:5
    at Array.forEach (native)
    at Object.<anonymous> (C:\Users\GGG\.atom\packages\autocompile-jade\node_modules\jade\bin\jade.js:135:9)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
```

Extra information:
- Using the same command the package tries to execute:
  `cmd /c C:\Users\GGG\.atom\packages\autocompile-jade\node_modules\.bin\jade --out "C:\Users\GGG\Desktop\[en]SQL Simulator" "C:\Users\GGG\Desktop\[en]SQL Simulator\index.jade"`
  works if executed directly on cmd.exe

EDIT: Sorry for taking so long to answer.

**Comment by paulpflug** [comment]
works for me now in windows..

**Comment by GGG-KILLER** [comment]
Works perfectly now, thank you!
